/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.coco;

public final class R {
    public static final class attr {
    }
    public static final class raw {
        public static final int borders=0x7f020000;
        public static final int centers=0x7f020001;
        public static final int colors=0x7f020002;
        public static final int diplomacy=0x7f020003;
        public static final int editor=0x7f020004;
        public static final int font=0x7f020005;
        public static final int font_frag=0x7f020006;
        public static final int font_vert=0x7f020007;
        public static final int gameplay=0x7f020008;
        public static final int logo=0x7f020009;
        public static final int main_menu=0x7f02000a;
        public static final int map_frag=0x7f02000b;
        public static final int map_vert=0x7f02000c;
        public static final int nation_select=0x7f02000d;
        public static final int provinces=0x7f02000e;
        public static final int terrain=0x7f02000f;
        public static final int title=0x7f020010;
        public static final int ui_frag=0x7f020011;
        public static final int ui_vert=0x7f020012;
    }
}
